### ISSUE TITLE
Errors with cocoapods

### ISSUE THREAD

**Issue by Oggerschummer** [LavaSlider/DSSparseArray#1]
Installation by cocoapods would be very beneficial. Could you add a podspec ?
I see there is one include but a pod "DSSparseArray" does not work, can´t find it.

Requires 
pod 'DSSparseArray', :git => 'https://github.com/LavaSlider/DSSparseArray.git', :branch => 'master'
to load, which is not very convenient.
Even then it does load the wrong files (Only AppDelegate.h/.m and main.m...)

**Comment by LavaSlider** [comment]
Hi Oggerschummer. I do not use podspecs. Can you put together the appropriately formatted file and I can add it to the repository?

**Comment by Oggerschummer** [comment]
Solved by Puill Requst #2

**Comment by LavaSlider** [comment]
Should be all set. Thanks for your help Oggerschummer.
